

# Set seed for reproducibility
library(Sim.DiffProc)
library(knitr)
knitr::opts_chunk$set(comment="",prompt=TRUE, fig.show='hold', warning=FALSE, message=FALSE)
options(prompt="R> ",scipen=16,digits=5,warning=FALSE, message=FALSE,
        width = 70)

set.seed(1234, kind = "L'Ecuyer-CMRG")

# Initial conditions
y0 = 0.572             # Initial value for S(t)
x0 = 0.12              # Initial value for Y(t)
r = 0.01               # Risk-free rate

# Ornstein-Uhlenbeck (OU) process parameters
gamma = 0.5           
rho = 0.3             
nu = 2.0           
theta = 0.5            
xi = 0.5               # Vol of vol in Y

# S(t) process parameters
a = 0.06               
b = 0.5                
sigma_S = 0.2          

# Option parameters
K = 0.1               
cp = 1                 # 1 for Call, 0 for Put
L = 0.1                # Lower barrier
U = 135.0              # Upper barrier

# Constraints for Y(t)
y_min = 1e-8           # Minimum Y(t) to avoid log(0)
y_max = 150.0        

# ---------------------------- #
#   Simulation of 2D SDEs      #
# ---------------------------- #
fx <- expression(nu*(theta-x),(exp(-a*x))*y)
cov_matrix <- matrix(c(xi^2, rho * xi * sigma_S,
                       rho * xi * sigma_S, sigma_S^2),
                     nrow = 2, byrow = TRUE)

# Cholesky decomposition to obtain the diffusion matrix
diffusion_matrix <- t(chol(cov_matrix))

gx <- expression(xi,sigma_S*x)

# Create the SDE object
sde_model <- snssde2d(
  drift = fx,
  diffusion = gx,
  Dt=0.01,
  M=1000,
  x0 = c(x0,y0),
  method = "smilstein", # Using Euler-Maruyama method
  bounds = list(Y = c(y_min, y_max), S = c(0, Inf)) # Enforce Y(t) bounds
)
sde_model
summary(sde_model, at = 10)
plot(sde_model)
plot2d(sde_model,type="n")
points2d(sde_model,col=rgb(0,100,0,50,maxColorValue=255), pch=16)

TEX.sde(object = sde_model, booktabs = TRUE, align = "r", caption ="LaTeX table for Monte Carlo results generated by `TEX.sde()` method.")

## the marginal density
denM <- dsde2d(sde_model,pdf="M",at =10)
plot(denM, main="Marginal Density")
## the Joint density
denJ <- dsde2d(sde_model, pdf="J", n=100,at =10)
plot(denJ,display="contour",main="Bivariate Transition Density at time t=10")
# Adjusting the plot window
par(mar = c(1, 1, 1, 1)) # Set margins: bottom, left, top, right

# Increase the plotting window size if you're using RStudio or a graphical device
x11(width = 10, height = 7) # Optional, to create a larger plotting window

# Plot with improved display
plot(
  denJ, 
  display = "persp", 
  main = "Bivariate Transition Density at time t=10", 
  theta = 30, # Adjust the viewing angle
  phi = 30,   # Adjust the viewing angle
  expand = 0.6, # Zoom in/out the plot
  shade = 0.5,  # Control shading of the surface
  cex.main = 1.5, # Text size for the main title
  cex.lab = 1.2,  # Text size for the axis labels
  cex.axis = 0.9  # Text size for the tick labels
)
